spring:
  freemarker:
    cache: true
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates
  application:
    name: app-mayikt-portal-web
server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.146:8080/eureka

