
###服务注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.146:8080/eureka/
###api网关端口号      
server:
  port: 80
###网关名称  
spring:
  application:
    name: app-mayikt-zuul
zuul:
  routes:
  ###定义转发服务规则
    api-a:
    ### 当客户端发送请求 127.0.0.1:80/api-member开头的 都会转发到会员服务
      path: /api-member/**
      ###服务别名  zuul网关默认整合ribbon 自动实现负载均衡轮训效果
      serviceId: app-mayikt-member
    api-b:
     ### 当客户端发送请求 127.0.0.1:80/api-order开头的 都会转发到订单服务
      path: /api-weixin/**
      ##订单服务别名
      serviceId: app-mayikt-weixin
###默认服务读取eureka注册服务列表 默认间隔30秒

###开启所有监控中心接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
