###服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-mayikt-weixin
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

swagger:
  base-package: com.wenhao.shop.service.weixin
  title: 微信服务接口
  description: 描述
  version: 1.1